repos:
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.10.2 # Replace by any tag/version ≥0.2.4 : https://github.com/snakemake/snakefmt/releases
    hooks:
      - id: snakefmt
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    # Run the linter.
      - id: ruff
        args: [ --fix ]
    # Run the formatter.
      - id: ruff-format
