output_folder: /cluster/work/bewi/members/jgawron/projects/Demultiplexing/AML_data/output
loom_files: /cluster/work/bewi/members/jgawron/projects/Demultiplexing/AML_data/loom_files_complete
seed: 123
n_samples: 10
max_pool_size: 4
doublet_rate: 0.1
downsampling: 5000