output_folder: /cluster/work/bewi/members/jgawron/projects/Demultiplexing/AML_data/output
loom_files: /cluster/work/bewi/members/jgawron/projects/Demultiplexing/AML_data/loom_files_complete
seed: __seed__
n_samples: 10
max_pool_size: 4
doublet_rate: __doublet_rate__
downsampling: __cell_count__
