#executor: slurm
latency-wait: 60
jobs: 500
#default-storage-provider: fs
#shared-fs-usage:
#  - persistence
#  - software-deployment
#  - sources
#  - source-cache


default-resources:
    mem_mb_per_cpu: 4096
    slurm_account: "'es_beere'"
    time: 240
    cores: 24
      #    software-deployment-method: conda
      #rerun-incomplete: True
      #keep-going: True

